### ISSUE TITLE
gitreleases.dev is down....

### ISSUE THREAD

**Issue by xiaods** [mweibel/gitreleases#6]

**Comment by xiaods** [comment]
any update？

**Comment by mweibel** [comment]
hey! sorry I was out of office for a while. My k8s cluster got fucked up. reinitializing now. Should be back soon.

**Comment by xiaods** [comment]
> hey! sorry I was out of office for a while. My k8s cluster got fucked up. reinitializing now. Should be back soon.

thanks for your sharing.

**Comment by mweibel** [comment]
it's up again
