### ISSUE TITLE
can't work for this service

### ISSUE THREAD

**Issue by xiaods** [mweibel/gitreleases#7]
always 0 size.

```
[root@ip-172-31-9-177 k8e]# curl https://gitreleases.dev/gh/xiaods/k8e/latest/k8e -o k8e
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
```

**Comment by mweibel** [comment]
hi, 
would need to check, but anyway is gitreleases outdated since a while as GitHub implemented the functionality natively. 
I suggest you use the direct link from GitHub instead: https://github.com/xiaods/k8e/releases/latest/download/k8e

thanks for reporting though.

**Comment by xiaods** [comment]
thanks for your share. it cool tips.
